@startuml
!include style.puml

skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Cookbook *-right-> "1" UniqueRecipeList
Cookbook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueRecipeList
UniqueTagList -[hidden]down- UniqueRecipeList

UniqueTagList *-right-> "*" Tag
UniqueRecipeList o-right-> Recipe

Recipe o-up-> "*" Tag

Recipe *--> RecipeName
Recipe *--> RecipeDescription
Recipe *--> UniqueIngredientList
Recipe *--> UniqueStepList
@enduml
