@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CookingPapaParser" as CookingPapaParser LOGIC_COLOR
participant ":CookbookCommandParser" as CookbookCommandParser LOGIC_COLOR
participant ":CookbookRemoveCommandParser" as CookbookRemoveCommandParser LOGIC_COLOR
participant "r:CookbookRemoveCommand" as CookbookRemoveCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("cookbook remove recipe 2")
activate LogicManager

LogicManager -> CookingPapaParser : parseCommand("cookbook remove recipe 2")
activate CookingPapaParser

create CookbookCommandParser
CookingPapaParser -> CookbookCommandParser
activate CookbookCommandParser

CookbookCommandParser -> CookingPapaParser
deactivate CookbookCommandParser

CookingPapaParser -> CookbookCommandParser : parse("remove recipe 2")
activate CookbookCommandParser

create CookbookRemoveCommandParser
CookbookCommandParser -> CookbookRemoveCommandParser :
activate CookbookRemoveCommandParser

CookbookRemoveCommandParser -> CookbookCommandParser
deactivate CookbookRemoveCommandParser

CookbookCommandParser -> CookbookRemoveCommandParser : parse("2")
activate CookbookRemoveCommandParser

create CookbookRemoveCommand
CookbookRemoveCommandParser -> CookbookRemoveCommand
activate CookbookRemoveCommand

CookbookRemoveCommand -> CookbookRemoveCommandParser : r
deactivate CookbookRemoveCommand

CookbookRemoveCommandParser -> CookbookCommandParser : r
deactivate CookbookRemoveCommandParser
CookbookRemoveCommandParser -[hidden]-> CookingPapaParser
destroy CookbookRemoveCommandParser

CookbookCommandParser -> CookingPapaParser : r
deactivate CookbookCommandParser

CookingPapaParser -> LogicManager : r
deactivate CookingPapaParser

LogicManager -> CookbookRemoveCommand : execute()
activate CookbookRemoveCommand

CookbookRemoveCommand -> Model : removeCookbookRecipe(2)
activate Model

Model --> CookbookRemoveCommand
deactivate Model

create CommandResult
CookbookRemoveCommand -> CommandResult
activate CommandResult

CommandResult --> CookbookRemoveCommand
deactivate CommandResult

CookbookRemoveCommand --> LogicManager : result
deactivate CookbookRemoveCommand

[<--LogicManager
deactivate LogicManager
@enduml
