@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CookingPapaParser" as CookingPapaParser LOGIC_COLOR
participant ":InventoryCommandParser" as InventoryCommandParser LOGIC_COLOR
participant ":InventoryRemoveIngredientCommandParser" as InventoryRemoveIngredientCommandParser LOGIC_COLOR
participant ":InventoryRemoveIngredientCommand" as InventoryRemoveIngredientCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("inventory remove ingredient i/Eggs q/5")
activate LogicManager

LogicManager -> CookingPapaParser : parseCommand("inventory remove ingredient i/Eggs q/5")
activate CookingPapaParser

create InventoryCommandParser
CookingPapaParser -> InventoryCommandParser
activate InventoryCommandParser

InventoryCommandParser -> CookingPapaParser
deactivate InventoryCommandParser

CookingPapaParser -> InventoryCommandParser : parse("remove ingredient i/Eggs q/5")
activate InventoryCommandParser

create InventoryRemoveIngredientCommandParser
InventoryCommandParser -> InventoryRemoveIngredientCommandParser :
activate InventoryRemoveIngredientCommandParser

InventoryRemoveIngredientCommandParser -> InventoryCommandParser
deactivate InventoryRemoveIngredientCommandParser

InventoryCommandParser -> InventoryRemoveIngredientCommandParser : parse("i/Eggs q/5")
activate InventoryRemoveIngredientCommandParser

create InventoryRemoveIngredientCommand
InventoryRemoveIngredientCommandParser -> InventoryRemoveIngredientCommand
activate InventoryRemoveIngredientCommand

InventoryRemoveIngredientCommand -> InventoryRemoveIngredientCommandParser : command
deactivate InventoryRemoveIngredientCommand

InventoryRemoveIngredientCommandParser -> InventoryCommandParser : command
deactivate InventoryRemoveIngredientCommandParser

InventoryCommandParser -> CookingPapaParser
deactivate InventoryCommandParser

CookingPapaParser -> LogicManager : command
deactivate CookingPapaParser

LogicManager -> InventoryRemoveIngredientCommand : execute()
activate InventoryRemoveIngredientCommand

InventoryRemoveIngredientCommand -> Model : removeInventoryIngredient(ingredient)
activate Model

Model --> InventoryRemoveIngredientCommand
deactivate Model

create CommandResult
InventoryRemoveIngredientCommand -> CommandResult
activate CommandResult

CommandResult --> InventoryRemoveIngredientCommand
deactivate CommandResult

InventoryRemoveIngredientCommand --> LogicManager : result
deactivate InventoryRemoveIngredientCommand

[<--LogicManager
deactivate LogicManager
@enduml
