@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyCookbook <<Interface>>
Interface ReadOnlyInventory <<Interface>>
Interface ReadOnlyCart <<Interface>>
Interface ReadOnlyIngredientList <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class CookingPapa
Class ReadOnlyCookbook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
Class ReadOnlyCart
Class ReadOnlyIngredientList
Class ReadOnlyInventory

Package Cart {
Class Cart
Class UniqueIngredientList
}

Package Inventory {
Class Inventory
Class UniqueIngredientList
}

Package Ingredient {
Class IngredientName
Class Ingredient
Class IngredientQuantity
}

Package Cookbook {
Class UniqueRecipeList
Class Cookbook
}

Package Recipe {
Class Recipe
Class Tag
Class UniqueStepList
Class RecipeName
Class RecipeDescription
Class UniqueIngredientList
}

Package UniqueIngredientList {
Class UniqueIngredientList
}

Package Step {
Class Step
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" Cookbook
ModelManager o--> "1" Cart
ModelManager o--> "1" Inventory

ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Cookbook .left--> UniqueRecipeList
Cookbook .up.|> ReadOnlyCookbook

Inventory .right--> UniqueIngredientList
Inventory .up.|> ReadOnlyInventory

Cart --> UniqueIngredientList
Cart .up.|> ReadOnlyCart

UniqueIngredientList .up.|> ReadOnlyIngredientList
Recipe --> RecipeName
Recipe --> RecipeDescription
Recipe --> UniqueStepList
Recipe --> Tag
Recipe -right-> UniqueIngredientList

UniqueStepList o--> "*" Step

UniqueIngredientList o--> "*" Ingredient
UniqueRecipeList o--> "*" Recipe
@enduml
