@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyCookbook <<Interface>>
Interface ReadOnlyInventory <<Interface>>
Interface ReadOnlyCart <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class Cookbook
Class ReadOnlyCookbook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
Class Inventory
Class ReadOnlyInventory
Class Cart
Class ReadOnlyCart
Class SortedIngredientList

Package Recipe {
Class Recipe
Class RecipeDescription
Class RecipeName
Class UniqueRecipeList
Class UniqueIngredientList
Class UniqueStepList
}

Package Ingredient {
Class CompatibleIngredientList
Class Ingredient
Class IngredientName
Class IngredientQuantity
}

Package Step {
Class Step
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Cookbook .up.|> ReadOnlyCookbook
Inventory .up.|> ReadOnlyInventory
Cart .up.|> ReadOnlyCart

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager -down-> "1" Cookbook
ModelManager -left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs
ModelManager -down-> "1" Inventory
ModelManager -down-> "1" Cart

Cookbook -[hidden]up-> UserPrefs

Cookbook *--> "1" UniqueRecipeList
UniqueRecipeList --> "*" Recipe
Recipe *--> "1" RecipeName
Recipe *--> "1" RecipeDescription
Recipe *--> "1" UniqueIngredientList
Recipe *--> "1" UniqueStepList
Recipe *--> "*" Tag

RecipeName -[hidden]right-> RecipeDescription
RecipeDescription -[hidden]right-> UniqueStepList
UniqueStepList -[hidden]right-> UniqueIngredientList

Tag -[hidden]right-> RecipeName
RecipeName -[hidden]right-> RecipeDescription
RecipeDescription -[hidden]right-> UniqueStepList
UniqueStepList -[hidden]right-> UniqueIngredientList

Inventory --|> SortedIngredientList
Cart --|> SortedIngredientList
SortedIngredientList *-down-> "1" CompatibleIngredientList
CompatibleIngredientList -left-|> UniqueIngredientList
CompatibleIngredientList -[hidden]down-|> Ingredient
UniqueIngredientList -down-> "*" Ingredient
Ingredient *-down-> "1" IngredientName
Ingredient *-down-> "1" IngredientQuantity

UniqueStepList *--> "*" Step

ModelManager -->"1" Recipe : filtered list
@enduml
