@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "inventory add ingredient i/Egg q/10"

package States <<rectangle>> {
    class State1 as "__cp0:CookingPapa__"
    class State2 as "__cp1:CookingPapa__"
    class State3 as "__cp2:CookingPapa__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFF

Pointer -up-> State3
@end
