= Goh Ka Hui - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Cooking Papa

---

== Overview

Cooking Papa is a desktop cookbook application used to manage recipes and ingredients for cooking. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 15 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to search for recipes based on the ingredients in the inventory*
** What it does: allows the user to find recipes that match the inventory ingredients best, sorted by the similarity to the inventory ingredients.
** Justification: This feature improves the product significantly because a user may not know what to cook with their ingredients, and the app should provide a convenient way to find the most suitable recipes to cook with the available ingredients.
** Highlights: This enhancement required an in-depth analysis of design alternatives. The implementation too was challenging as it required a robust way of handling ingredient quantities.
** Credits: https://commons.apache.org/proper/commons-math/[Apache Commons Math] (The `Fraction` class was used in implementing ingredient quantities)

* *Minor enhancement*:

* *Code contributed*: https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#=undefined&search=gohkh[Link]

* *Other contributions*:

** Project management:

** Enhancements to existing features:

** Documentation:

** Community:
*** PRs reviewed (with non-trivial comments):
https://github.com/AY1920S2-CS2103T-F11-4/main/pull/18[#18],
https://github.com/AY1920S2-CS2103T-F11-4/main/pull/57[#57],
https://github.com/AY1920S2-CS2103T-F11-4/main/pull/61[#61],
https://github.com/AY1920S2-CS2103T-F11-4/main/pull/90[#90],
https://github.com/AY1920S2-CS2103T-F11-4/main/pull/92[#92],
https://github.com/AY1920S2-CS2103T-F11-4/main/pull/99[#99],
https://github.com/AY1920S2-CS2103T-F11-4/main/pull/113[#113],
https://github.com/AY1920S2-CS2103T-F11-4/main/pull/122[#122],
https://github.com/AY1920S2-CS2103T-F11-4/main/pull/131[#131],
https://github.com/AY1920S2-CS2103T-F11-4/main/pull/139[#139],
https://github.com/AY1920S2-CS2103T-F11-4/main/pull/160[#160],
https://github.com/AY1920S2-CS2103T-F11-4/main/pull/208[#208]

** Tools:
*** Integrated a third-party library, https://commons.apache.org/proper/commons-math/[Apache Commons Math], to the project (https://github.com/AY1920S2-CS2103T-F11-4/main/pull/60[#60])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=cookbooksearchinventory]
